package sfsu.csc413.foodcraft;


import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;


/**
 * Created by pklein on 11/2/15.
 */
public class IngredientList {

    public ArrayList<String> ingredients = new ArrayList<>();


    IngredientList(){
        ingredients.add("apple");
        ingredients.add("abalone");
        ingredients.add("agave nectar");
        ingredients.add("all-purpose flour");
        ingredients.add("allspice");
        ingredients.add("almond");
        ingredients.add("almond butter");
        ingredients.add("almond milk");
        ingredients.add("andouille sausage");
        ingredients.add("anelli");
        ingredients.add("anise");
        ingredients.add("apple cider vinegar");
        ingredients.add("apricot");
        ingredients.add("apricot jam");
        ingredients.add("arborio rice");
        ingredients.add("arm roast");
        ingredients.add("artichoke");
        ingredients.add("arugula");
        ingredients.add("asparagus");
        ingredients.add("avocado");
        ingredients.add("avocado oil");
        ingredients.add("baby carrot");
        ingredients.add("baby kale");
        ingredients.add("baby spinach");
        ingredients.add("bacon");
        ingredients.add("bacon pieces");
        ingredients.add("baking powder");
        ingredients.add("baking soda");
        ingredients.add("balsamic vinegar");
        ingredients.add("banana");
        ingredients.add("barley");
        ingredients.add("basil");
        ingredients.add("bavette");
        ingredients.add("bay leaf");
        ingredients.add("beef bouillon");
        ingredients.add("beef broth");
        ingredients.add("beet");
        ingredients.add("bell pepper");
        ingredients.add("bilberry");
        ingredients.add("bisquick");
        ingredients.add("black bean");
        ingredients.add("black pepper");
        ingredients.add("blackberry");
        ingredients.add("blackcurrant");
        ingredients.add("blood orange");
        ingredients.add("blueberry");
        ingredients.add("bok choy");
        ingredients.add("boneless chicken breast");
        ingredients.add("bourbon whiskey");
        ingredients.add("boysenberry");
        ingredients.add("bread flour");
        ingredients.add("brisket steak");
        ingredients.add("broccoli");
        ingredients.add("brown hash potato");
        ingredients.add("brown lentil");
        ingredients.add("brown rice");
        ingredients.add("brown sugar");
        ingredients.add("brussel sprout");
        ingredients.add("bucatini");
        ingredients.add("buckwheat flour");
        ingredients.add("butter");
        ingredients.add("buttermilk");
        ingredients.add("butternut squash");
        ingredients.add("cabbage");
        ingredients.add("cajun spice mix");
        ingredients.add("cake");
        ingredients.add("campanelle");
        ingredients.add("canadian bacon");
        ingredients.add("candied pecan");
        ingredients.add("cane sugar");
        ingredients.add("cannelloni");
        ingredients.add("canola oil");
        ingredients.add("cantaloupe");
        ingredients.add("capellini");
        ingredients.add("caper");
        ingredients.add("caraway");
        ingredients.add("cardamom");
        ingredients.add("cardamon");
        ingredients.add("carrot");
        ingredients.add("carrots");
        ingredients.add("cashew milk");
        ingredients.add("cassava");
        ingredients.add("caster sugar");
        ingredients.add("catfish");
        ingredients.add("catnip");
        ingredients.add("cauliflower");
        ingredients.add("caviar");
        ingredients.add("cayenne pepper");
        ingredients.add("celery");
        ingredients.add("celery rib");
        ingredients.add("celery seed");
        ingredients.add("chayote");
        ingredients.add("cheddar cheese");
        ingredients.add("cheese");
        ingredients.add("cheese tortellini");
        ingredients.add("cherimoya");
        ingredients.add("cherry");
        ingredients.add("chevre");
        ingredients.add("chia seed");
        ingredients.add("chicken");
        ingredients.add("chicken bone");
        ingredients.add("chicken breast");
        ingredients.add("chicken breast");
        ingredients.add("chicken broth");
        ingredients.add("chicken sausage");
        ingredients.add("chicken stock");
        ingredients.add("chicken thigh");
        ingredients.add("chickpea");
        ingredients.add("chicory");
        ingredients.add("chili pepper");
        ingredients.add("chili powder");
        ingredients.add("chipotle pepper");
        ingredients.add("chives");
        ingredients.add("chocolate chip");
        ingredients.add("chocolate syrup");
        ingredients.add("chuck roast");
        ingredients.add("chuck roast");
        ingredients.add("chutney");
        ingredients.add("cilantro");
        ingredients.add("cinnamon");
        ingredients.add("cinnamon stick");
        ingredients.add("ciriole");
        ingredients.add("clementine");
        ingredients.add("cloudberry");
        ingredients.add("clove");
        ingredients.add("cloves");
        ingredients.add("club steak");
        ingredients.add("coarse salt");
        ingredients.add("cocoa powder");
        ingredients.add("coconut");
        ingredients.add("coconut milk");
        ingredients.add("coconut oil");
        ingredients.add("coconut sugar");
        ingredients.add("coconut water");
        ingredients.add("coffee");
        ingredients.add("coleslaw");
        ingredients.add("collard greens");
        ingredients.add("coriander");
        ingredients.add("coriander seed");
        ingredients.add("corn starch");
        ingredients.add("corn tortilla");
        ingredients.add("cottage cheese");
        ingredients.add("crab");
        ingredients.add("cranberry");
        ingredients.add("cream cheese");
        ingredients.add("cream of chicken soup");
        ingredients.add("cremini mushroom");
        ingredients.add("crisco");
        ingredients.add("crushed tomato");
        ingredients.add("cucumber");
        ingredients.add("cumin");
        ingredients.add("cumin seed");
        ingredients.add("currant");
        ingredients.add("curry leaf");
        ingredients.add("damson");
        ingredients.add("dark brown sugar");
        ingredients.add("dark chocolate");
        ingredients.add("dark chocolate chip");
        ingredients.add("date");
        ingredients.add("deli ham");
        ingredients.add("dijon mustard");
        ingredients.add("dill");
        ingredients.add("dill pickle");
        ingredients.add("double cream");
        ingredients.add("dragon fruit");
        ingredients.add("dragonfruit");
        ingredients.add("dressing");
        ingredients.add("dry coconut");
        ingredients.add("dry milk powder");
        ingredients.add("dry mustard");
        ingredients.add("durian");
        ingredients.add("egg");
        ingredients.add("egg white");
        ingredients.add("elderberry");
        ingredients.add("endive");
        ingredients.add("extra virgin coconut oil");
        ingredients.add("extra-virgin olive oil");
        ingredients.add("fagottini");
        ingredients.add("farfalle");
        ingredients.add("farfalline");
        ingredients.add("fat-free milk");
        ingredients.add("fava bean");
        ingredients.add("feijoa");
        ingredients.add("fennel");
        ingredients.add("fettuccine");
        ingredients.add("fig");
        ingredients.add("flank steak");
        ingredients.add("flour tortilla");
        ingredients.add("fusilli");
        ingredients.add("garbanzo");
        ingredients.add("garbanzo beans");
        ingredients.add("garlic");
        ingredients.add("garlic clove");
        ingredients.add("garlic paste");
        ingredients.add("garlic powder");
        ingredients.add("garlic salt");
        ingredients.add("garnet yam");
        ingredients.add("gemelli");
        ingredients.add("gigli");
        ingredients.add("ginger");
        ingredients.add("gnocchi");
        ingredients.add("goji berry");
        ingredients.add("gold potato");
        ingredients.add("golden raisin");
        ingredients.add("gooseberry");
        ingredients.add("gourd");
        ingredients.add("grape");
        ingredients.add("grape leaves");
        ingredients.add("grape tomato");
        ingredients.add("grapefruit");
        ingredients.add("greek yogurt");
        ingredients.add("green bean");
        ingredients.add("green bell pepper");
        ingredients.add("green lentil");
        ingredients.add("green onion");
        ingredients.add("green pepper");
        ingredients.add("ground beef");
        ingredients.add("ground beef");
        ingredients.add("ground black pepper");
        ingredients.add("ground chicken");
        ingredients.add("ground cinnamon");
        ingredients.add("guava");
        ingredients.add("ham");
        ingredients.add("hamburger bun");
        ingredients.add("heavy cream");
        ingredients.add("honey");
        ingredients.add("honeydew");
        ingredients.add("horseradish");
        ingredients.add("huckleberry");
        ingredients.add("ice cube");
        ingredients.add("instant coffee");
        ingredients.add("italian sausage");
        ingredients.add("italian sausages");
        ingredients.add("italian seasoning");
        ingredients.add("jabouticaba");
        ingredients.add("jackfruit");
        ingredients.add("jalapeno chili");
        ingredients.add("jambul");
        ingredients.add("jasmine");
        ingredients.add("jicama");
        ingredients.add("jujube");
        ingredients.add("juniper berry");
        ingredients.add("kalamata");
        ingredients.add("kale");
        ingredients.add("kemon");
        ingredients.add("ketchup");
        ingredients.add("khoa");
        ingredients.add("kidney bean");
        ingredients.add("kiwi fruit");
        ingredients.add("kosher salt");
        ingredients.add("kumquat");
        ingredients.add("lasagne");
        ingredients.add("lavender");
        ingredients.add("leek");
        ingredients.add("lemon juice");
        ingredients.add("lemon zest");
        ingredients.add("lemongrass");
        ingredients.add("lentil");
        ingredients.add("lettuce");
        ingredients.add("licorice");
        ingredients.add("lima bean");
        ingredients.add("lime");
        ingredients.add("lime juice");
        ingredients.add("lime wedge");
        ingredients.add("linguine");
        ingredients.add("lobster");
        ingredients.add("loin steak");
        ingredients.add("long-grain rice");
        ingredients.add("loquat");
        ingredients.add("low sodium chicken");
        ingredients.add("low-fat cream cheese");
        ingredients.add("lychee");
        ingredients.add("macaroni");
        ingredients.add("mace");
        ingredients.add("mandarine");
        ingredients.add("mango");
        ingredients.add("manicotti");
        ingredients.add("maple syrup");
        ingredients.add("margarine");
        ingredients.add("marion berry");
        ingredients.add("marjoram");
        ingredients.add("marzipan");
        ingredients.add("mayonnaise");
        ingredients.add("melon");
        ingredients.add("meringue powder");
        ingredients.add("milk");
        ingredients.add("milk chocolate chip");
        ingredients.add("millet");
        ingredients.add("mini chocolate chip");
        ingredients.add("mint");
        ingredients.add("mint extract");
        ingredients.add("miracle fruit");
        ingredients.add("molasses");
        ingredients.add("moth bean");
        ingredients.add("mozarella");
        ingredients.add("mozzarella cheese");
        ingredients.add("mulberry");
        ingredients.add("mung bean");
        ingredients.add("mustard");
        ingredients.add("mustard green");
        ingredients.add("mustard seed");
        ingredients.add("napa cabbage");
        ingredients.add("nectarine");
        ingredients.add("nutmeg");
        ingredients.add("oat");
        ingredients.add("okra");
        ingredients.add("old-fashioned oats");
        ingredients.add("olive");
        ingredients.add("olive oil");
        ingredients.add("onion");
        ingredients.add("onion powder");
        ingredients.add("orange");
        ingredients.add("orange peel");
        ingredients.add("orange zest");
        ingredients.add("oregano");
        ingredients.add("orzo");
        ingredients.add("oscar mayer bacon");
        ingredients.add("pappardelle");
        ingredients.add("paprika");
        ingredients.add("parmesan cheese");
        ingredients.add("parsley");
        ingredients.add("parsley flakes");
        ingredients.add("parsnip");
        ingredients.add("pasta shells");
        ingredients.add("pea");
        ingredients.add("peach");
        ingredients.add("peanut");
        ingredients.add("peanut butter");
        ingredients.add("pear");
        ingredients.add("pecan");
        ingredients.add("penne");
        ingredients.add("pepper");
        ingredients.add("peppermint extract");
        ingredients.add("pepperoni");
        ingredients.add("persimmon");
        ingredients.add("physalis");
        ingredients.add("pici");
        ingredients.add("pickle");
        ingredients.add("pineapple");
        ingredients.add("pink peppercorn");
        ingredients.add("pizza dough");
        ingredients.add("pizza sauce");
        ingredients.add("plain greek yogurt");
        ingredients.add("plain yogurt");
        ingredients.add("plate steak");
        ingredients.add("plum");
        ingredients.add("plum tomato");
        ingredients.add("pomegranate");
        ingredients.add("pomelo");
        ingredients.add("poppy seed dressing");
        ingredients.add("pork belly");
        ingredients.add("pork loin");
        ingredients.add("pork roast");
        ingredients.add("pork shoulder");
        ingredients.add("pork tenderloin");
        ingredients.add("porterhouse steak");
        ingredients.add("pot roast");
        ingredients.add("potato");
        ingredients.add("powdered milk");
        ingredients.add("powdered sugar");
        ingredients.add("prune");
        ingredients.add("pumpkin");
        ingredients.add("pumpkin seed");
        ingredients.add("purple mangosteen");
        ingredients.add("purple onion");
        ingredients.add("quince");
        ingredients.add("quinoa");
        ingredients.add("radish");
        ingredients.add("raisin");
        ingredients.add("rambutan");
        ingredients.add("ranch dressing");
        ingredients.add("ranch-style seasoning");
        ingredients.add("raspberry");
        ingredients.add("ravioli");
        ingredients.add("red bell pepper");
        ingredients.add("red cabbage");
        ingredients.add("red chili pepper");
        ingredients.add("red lentil");
        ingredients.add("red onion");
        ingredients.add("red pepper flakes");
        ingredients.add("red potato");
        ingredients.add("red vinegar");
        ingredients.add("red wine");
        ingredients.add("red wine vinegar");
        ingredients.add("redcurrant");
        ingredients.add("rib chop");
        ingredients.add("rib roast");
        ingredients.add("rib steak");
        ingredients.add("rice flour");
        ingredients.add("rice vinegar");
        ingredients.add("ricotta cheese");
        ingredients.add("rigatoni");
        ingredients.add("romano cheese");
        ingredients.add("rosemary");
        ingredients.add("rotini");
        ingredients.add("rum");
        ingredients.add("rump roast");
        ingredients.add("russet potato");
        ingredients.add("rutabaga");
        ingredients.add("rye");
        ingredients.add("saffron");
        ingredients.add("sage");
        ingredients.add("salal berry");
        ingredients.add("salmon");
        ingredients.add("salmonberry");
        ingredients.add("salt");
        ingredients.add("sandwich roll");
        ingredients.add("sassafras");
        ingredients.add("satsuma");
        ingredients.add("savory");
        ingredients.add("scallions");
        ingredients.add("sea salt");
        ingredients.add("seasoning salt");
        ingredients.add("sesame seed");
        ingredients.add("shallot");
        ingredients.add("sharp cheddar");
        ingredients.add("sharp cheddar cheese");
        ingredients.add("shishito chile");
        ingredients.add("short ribs");
        ingredients.add("shoulder steak");
        ingredients.add("shrimp");
        ingredients.add("sirloin steak");
        ingredients.add("skim milk");
        ingredients.add("smoked paprika");
        ingredients.add("smoked sausage");
        ingredients.add("snap pea");
        ingredients.add("snow pea");
        ingredients.add("sorghum");
        ingredients.add("sour cream");
        ingredients.add("soy sauce");
        ingredients.add("soybean");
        ingredients.add("spaghetti");
        ingredients.add("spare ribs");
        ingredients.add("spinach");
        ingredients.add("sprouts");
        ingredients.add("squash");
        ingredients.add("sriracha");
        ingredients.add("star fruit");
        ingredients.add("stew meat");
        ingredients.add("strawberry");
        ingredients.add("string bean");
        ingredients.add("sugar");
        ingredients.add("sweet onion");
        ingredients.add("sweet pepper");
        ingredients.add("sweet pickle");
        ingredients.add("sweet potato");
        ingredients.add("swiss cheese");
        ingredients.add("t-bone steak");
        ingredients.add("tamarillo");
        ingredients.add("tamarind");
        ingredients.add("tangerine");
        ingredients.add("taro");
        ingredients.add("tarragon");
        ingredients.add("thyme");
        ingredients.add("tilapia");
        ingredients.add("toast");
        ingredients.add("tomatillo");
        ingredients.add("tomato");
        ingredients.add("tomato paste");
        ingredients.add("tomato sauce");
        ingredients.add("tomatoes");
        ingredients.add("tortellini");
        ingredients.add("tumeric");
        ingredients.add("turkey sausage");
        ingredients.add("turmeric");
        ingredients.add("turnip");
        ingredients.add("unsalted butter");
        ingredients.add("unsweetened cocoa powder");
        ingredients.add("unsweetened coconut water");
        ingredients.add("vanilla");
        ingredients.add("vanilla bean paste");
        ingredients.add("vanilla extract");
        ingredients.add("vanilla ice cream");
        ingredients.add("vegetable broth");
        ingredients.add("vegetable oil");
        ingredients.add("vegetable stock");
        ingredients.add("vermicelli");
        ingredients.add("vinegar");
        ingredients.add("walnut");
        ingredients.add("wasabi");
        ingredients.add("water");
        ingredients.add("watercress");
        ingredients.add("watermelon");
        ingredients.add("wheat flour");
        ingredients.add("wheatgrass");
        ingredients.add("whipped cream");
        ingredients.add("whipping cream");
        ingredients.add("white bread");
        ingredients.add("white flour");
        ingredients.add("white miso");
        ingredients.add("white mushroom");
        ingredients.add("white onion");
        ingredients.add("white pepper");
        ingredients.add("white rice");
        ingredients.add("white sugar");
        ingredients.add("white vinegar");
        ingredients.add("white wine");
        ingredients.add("whole milk");
        ingredients.add("wild rice");
        ingredients.add("wintergreen");
        ingredients.add("worcestershire sauce");
        ingredients.add("yam");
        ingredients.add("yeast");
        ingredients.add("yellow mustard");
        ingredients.add("yellow onion");
        ingredients.add("yukon gold potato");
        ingredients.add("ziti");
        ingredients.add("zucchini");
    }
    public boolean Contains(String ingredient_part){
        return ingredients.contains(ingredient_part);

    }
}
